[2024-04-15 18:00:21.595][  INFO   ]|     logger.py      |MOD:       logger       |FUNC:      <module>      |Line:145 [LOG] test
[2024-04-15 18:00:21.744][  INFO   ]|    read_yaml.py    |MOD:     read_yaml      |FUNC:     read_yaml      |Line: 16 [LOG] ./config/config.yaml配置字读取成功,读到的内容为{'prject': 'a8e', 'devices': '192.168.7.16:5555', 'qnx_ip': '192.168.118.2', 'qnx_user': 'root', 'qnx_passwd': '', 'qnx_screenshot_path': '/var/share/', 'adb_pull_source': '/data/nfs/nfs_share/screenshot.bmp', 'adb_pull_dest': './test/output_images/', 'android_log_path': '/mnt/user/log_android/', 'qnx_log_path': '/data/nfs/nfs_log/', 'cfg_path': './common/can/canoe_project/Configuration.cfg', 'dbc_path': './common/can/canoe_project/A8E_Proj_IHU_PFET_CMX+V1.25_20230421.dbc', 'video_path': 'E:/工作文档/学习文档/自动化/cluster_autotest/testdata', 'camera_index': 0, 'video_fps': 25}
[2024-04-15 18:00:22.109][  INFO   ]|    read_yaml.py    |MOD:     read_yaml      |FUNC:     read_yaml      |Line: 16 [LOG] ./config/config.yaml配置字读取成功,读到的内容为{'prject': 'a8e', 'devices': '192.168.7.16:5555', 'qnx_ip': '192.168.118.2', 'qnx_user': 'root', 'qnx_passwd': '', 'qnx_screenshot_path': '/var/share/', 'adb_pull_source': '/data/nfs/nfs_share/screenshot.bmp', 'adb_pull_dest': './test/output_images/', 'android_log_path': '/mnt/user/log_android/', 'qnx_log_path': '/data/nfs/nfs_log/', 'cfg_path': './common/can/canoe_project/Configuration.cfg', 'dbc_path': './common/can/canoe_project/A8E_Proj_IHU_PFET_CMX+V1.25_20230421.dbc', 'video_path': 'E:/工作文档/学习文档/自动化/cluster_autotest/testdata', 'camera_index': 0, 'video_fps': 25}
[2024-04-15 18:00:28.148][  INFO   ]|       qnx.py       |MOD:        qnx         |FUNC:      __init__      |Line: 33 [LOG] 执行成功,执行状态码为None。
[2024-04-15 18:00:34.218][  INFO   ]|       qnx.py       |MOD:        qnx         |FUNC:   qnx_screenshot   |Line: 54 [LOG] 执行成功,执行状态码为0
[2024-04-15 18:00:34.296][  INFO   ]|       adb.py       |MOD:        adb         |FUNC:   adb_pull_image   |Line: 66 [LOG] adb -s 192.168.7.16:5555 pull /data/nfs/nfs_share/screenshot.bmp ./test/output_images//screenshot_20240415-180034.bmp执行成功,执行状态码为1
[2024-04-15 18:00:34.309][  ERROR  ]|     images.py      |MOD:       images       |FUNC:compare_by_matrix_in_same_area|Line: 67 [LOG] [Errno 2] No such file or directory: './test/output_images//screenshot_20240415-180034.bmp'
[2024-04-15 18:00:38.535][  INFO   ]|       adb.py       |MOD:        adb         |FUNC:    del_iviimage    |Line:122 [LOG] 执行成功,执行状态码为1
[2024-04-15 18:00:42.548][  INFO   ]|       adb.py       |MOD:        adb         |FUNC:    del_qnximage    |Line:100 [LOG] 执行成功,执行状态码为1
