{"name": "test_02_eps", "status": "failed", "statusDetails": {"message": "AssertionError: assert (56, 0, 516, 52) == None", "trace": "self = <cluster_autotest.testcases.test_a8e.TestUint_Warning object at 0x00000252C43CFE50>\n\n    def test_02_eps(self):\n        test_qnx = qnx.qnx(\"1234567\",\"192.168.118.2\",\"root\",\"\")\n        test_qnx.qnx_screenshot(\"/var/share/\")\n        test = adb.adb.adb_pull_image(\"1234567\",\n                                    \"/data/nfs/nfs_share/screenshot.bmp\",\n                                    \"./cluster_autotest/testdata/actual/\")\n        test_image=images.Images()\n        test_result = test_image.compare_by_matrix_in_same_area(\"./cluster_autotest/testdata/expect/screenshot_warning.bmp\",\n                                                                test,\n                                                                (711,24,1227,80))\n        #screenshot = Image.open(\"./cluster_autotest/testdata/expect/screenshot_warning.bmp\")\n        #screenshot.save(\"./cluster_autotest/testdata/expect/screenshot_warning.png\", \"PNG\")\n        allure.attach.file(\"./cluster_autotest/testdata/expect/screenshot_warning.bmp\", name=\"Expected Result\", attachment_type=allure.attachment_type.BMP)\n        #allure.attach.file(test, name=\"Screenshot\", attachment_type=allure.attachment_type.PNG)\n>       assert test_result == None\nE       assert (56, 0, 516, 52) == None\n\ncluster_autotest\\testcases\\test_a8e.py:53: AssertionError"}, "attachments": [{"name": "Expected Result", "source": "815dd779-9b69-4fa0-926d-3e57335e8a15-attachment.bmp", "type": "image/bmp"}], "start": 1709621155691, "stop": 1709621161151, "uuid": "cac115b0-8049-4018-adfb-b4c00ed338b1", "historyId": "a892a8a8bbd79074841231c4de87a694", "testCaseId": "a892a8a8bbd79074841231c4de87a694", "fullName": "cluster_autotest.testcases.test_a8e.TestUint_Warning#test_02_eps", "labels": [{"name": "parentSuite", "value": "cluster_autotest.testcases"}, {"name": "suite", "value": "test_a8e"}, {"name": "subSuite", "value": "TestUint_Warning"}, {"name": "host", "value": "test-1"}, {"name": "thread", "value": "16572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cluster_autotest.testcases.test_a8e"}]}