[2024-03-13 15:23:34.609][  INFO   ]|     logger.py      |MOD:       logger       |FUNC:      <module>      |Line:145 [LOG] test
[2024-03-13 15:23:34.965][  INFO   ]|    read_yaml.py    |MOD:     read_yaml      |FUNC:     read_yaml      |Line: 16 [LOG] ./config/config.yaml配置字读取成功,读到的内容为{'prject': 'a8e', 'devices': '192.168.7.16:5555', 'qnx_ip': '192.168.118.2', 'qnx_user': 'root', 'qnx_passwd': '', 'qnx_screenshot_path': '/var/share/', 'adb_pull_source': '/data/nfs/nfs_share/screenshot.bmp', 'adb_pull_dest': './testdata/actual/', 'android_log_path': '/mnt/user/log_android/', 'qnx_log_path': '/data/nfs/nfs_log/', 'cfg_path': 'E:/工作文档\\学习文档/自动化/cluster_autotest/common/canoe_project/Configuration.cfg', 'dbc_path': './common/canoe_project/A8E_Proj_IHU_PFET_CMX+V1.25_20230421.dbc'}
[2024-03-13 15:23:44.720][  INFO   ]|       can.py       |MOD:        can         |FUNC:      __init__      |Line: 84 [LOG] Loaded CANoe version 
[2024-03-13 15:23:44.766][  INFO   ]|       can.py       |MOD:        can         |FUNC:      __init__      |Line: 89 [LOG] CANoe初始化成功
[2024-03-13 15:23:45.689][ WARNING ]|       can.py       |MOD:        can         |FUNC:      open_cfg      |Line:105 [LOG] opening...E:/工作文档\学习文档/自动化/cluster_autotest/common/canoe_project/Configuration.cfg
[2024-03-13 15:23:45.755][  ERROR  ]|       can.py       |MOD:        can         |FUNC: start_Measurement  |Line:148 [LOG] (-2147352567, '发生意外。', (0, 'Measurement::Start', 'Function is only available with valid application license.', 'C:\\Program Files\\Vector CANoe 12.0\\Help01\\CANoeCANalyzer.chm', 4470, -2147418113), None)
[2024-03-13 15:23:46.013][  INFO   ]|    read_yaml.py    |MOD:     read_yaml      |FUNC:     read_yaml      |Line: 16 [LOG] ./config/config.yaml配置字读取成功,读到的内容为{'prject': 'a8e', 'devices': '192.168.7.16:5555', 'qnx_ip': '192.168.118.2', 'qnx_user': 'root', 'qnx_passwd': '', 'qnx_screenshot_path': '/var/share/', 'adb_pull_source': '/data/nfs/nfs_share/screenshot.bmp', 'adb_pull_dest': './testdata/actual/', 'android_log_path': '/mnt/user/log_android/', 'qnx_log_path': '/data/nfs/nfs_log/', 'cfg_path': 'E:/工作文档\\学习文档/自动化/cluster_autotest/common/canoe_project/Configuration.cfg', 'dbc_path': './common/canoe_project/A8E_Proj_IHU_PFET_CMX+V1.25_20230421.dbc'}
[2024-03-13 15:23:52.080][  INFO   ]|       qnx.py       |MOD:        qnx         |FUNC:      __init__      |Line: 33 [LOG] 执行成功,执行状态码为None。
[2024-03-13 15:23:58.126][  INFO   ]|       qnx.py       |MOD:        qnx         |FUNC:   qnx_screenshot   |Line: 54 [LOG] 执行成功,执行状态码为0
[2024-03-13 15:23:59.571][  INFO   ]|       adb.py       |MOD:        adb         |FUNC:   adb_pull_image   |Line: 65 [LOG] adb -s 192.168.7.16:5555 pull /data/nfs/nfs_share/screenshot.bmp ./testdata/actual//screenshot_20240313-152358.bmp执行成功,执行状态码为0
